version: "3.8"
services:

    db:
        image: mysql
        container_name: db_docker
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_docker
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    www:
        build: php
        container_name: symfony_docker
        ports:
          - "8741:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev

    # app:
    #   build: tricount
    #   container_name: app_react
    #   ports:
    #     - "3000:3000"
    #   volumes:
    #     - "./tricount:/app"
    #   command: sh -c "npm i && npm run start"

networks:
    dev:

volumes:
    db-data:
